"""empty message

Revision ID: 0421743322e3
Revises: dd4063d52a27
Create Date: 2025-04-29 20:36:09.251433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0421743322e3'
down_revision = 'dd4063d52a27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.drop_index('ix_Users_email')
        batch_op.create_index(batch_op.f('ix_Users_email'), ['email'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Users_email'))
        batch_op.create_index('ix_Users_email', ['email'], unique=1)

    # ### end Alembic commands ###
